version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookhub-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/bookhub
      - PORT=5000
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - bookhub-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookhub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bookhub-network

  mongo:
    image: mongo:6
    container_name: bookhub-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=bookhub
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - bookhub-network

volumes:
  mongodb_data:

networks:
  bookhub-network:
    driver: bridge